site_name: SSCC QC Basic
site_url: https://nruneberg.github.io/sscc-qc-basic/
repo_url: https://github.com/nruneberg/sscc-qc-basic
theme:
  name: material
  logo: img/tmolex-and-puhti.svg
  favicon: img/tmolex-and-puhti.svg

nav:
  - Home: index.md
  - Preparations: preparations/README.md
  - Tutorial 1: tutorial1/README.md
  - Tutorial 2: tutorial2/README.md

extra_css:
  - stylesheets/custom.css
